### ISSUE TITLE
.net core2.2 web工程使用发布后运行异常

### ISSUE THREAD

**Issue by wenjq0911** [dotnetcore/Natasha#10]
在.net core2.2环境下，使用vs2017开发web，调试运行没有任何问题，动态编译正常运行。独立发布后运行出现异常，主要异常信息如下：
```
Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
      An unhandled exception has occurred while executing the request.
System.ArgumentOutOfRangeException: Length cannot be less than zero.
Parameter name: length
   at System.String.Substring(Int32 startIndex, Int32 length)
   at Natasha.Complier.ScriptComplierEngine.GetErrorString(String content, FileLinePositionSpan linePositionSpan) in C:\Users\wenjq\Downloads\Natasha-master\src\Natasha\Engine\ComplierModule\ScriptComplierEngine.cs:line 428
   at Natasha.Complier.ScriptComplierEngine.StreamComplier(String sourceContent, String& formatContent, Action`1 errorAction) in C:\Users\wenjq\Downloads\Natasha-master\src\Natasha\Engine\ComplierModule\ScriptComplierEngine.cs:line 202
   at Natasha.IComplier.GetAssemblyByScript(String content) in C:\Users\wenjq\Downloads\Natasha-master\src\Natasha\Engine\Standard\IComplier.cs:line 69
   at Natasha.IComplier.GetTypeByScript(String content, String typeName) in C:\Users\wenjq\Downloads\Natasha-master\src\Natasha\Engine\Standard\IComplier.cs:line 105
   at Natasha.IComplier.GetMethodByScript(String content, String typeName, String methodName) in C:\Users\wenjq\Downloads\Natasha-master\src\Natasha\Engine\Standard\IComplier.cs:line 138
   at Natasha.IComplier.GetDelegateByScript(String content, String typeName, String methodName, Type delegateType, Object binder) in C:\Users\wenjq\Downloads\Natasha-master\src\Natasha\Engine\Standard\IComplier.cs:line 174
   at Natasha.IComplier.GetDelegateByScript[T](String content, String typeName, String methodName, Object binder) in C:\Users\wenjq\Downloads\Natasha-master\src\Natasha\Engine\Standard\IComplier.cs:line 205
   at Natasha.Complier.MethodComplier.Complie[T](String className, String content, String methodName, Object binder) in C:\Users\wenjq\Downloads\Natasha-master\src\Natasha\Complier\MethodComplier.cs:line 45
   at Natasha.Builder.OnceMethodBuilder`1.Complie[T](Object binder) in C:\Users\wenjq\Downloads\Natasha-master\src\Natasha\Builder\OnceMethodBuilder.cs:line 51
   at Natasha.FastMethodOperator.Complie[T](Object binder) in C:\Users\wenjq\Downloads\Natasha-master\src\Natasha\Operator\FastMethodOperator.cs:line 57
```
尝试附件进程调试，发现在ScriptComplierEngine的StreamComplier方法，诊断信息中产生了大量的警告信息，导致GetErrorString出错。修改代码只取Error信息后得到下面的错误提示：
```
------------------------------------------error----------------------------------------------

    Time :		2019-08-06 15:32:30

    Lauguage :	C# & CSharp7_3

    Target:		System.String[]

    Error:		共9处错误！
		第7行，第20个字符：       内容【N88d54917fd80421d93a7d1d1eee7587f】  预定义类型“System.Object”未定义或导入
		第9行，第46个字符：       内容【Object】  预定义类型“System.Object”未定义或导入
		第9行，第46个字符：       内容【Object】  未能在命名空间“System”中找到类型名“Object”。此类型已转发到程序集“System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e”。请考虑添加对该程序集的引用。
		第9行，第18个字符：       内容【Object】  预定义类型“System.Object”未定义或导入
		第9行，第18个字符：       内容【Object】  未能在命名空间“System”中找到类型名“Object”。此类型已转发到程序集“System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e”。请考虑添加对该程序集的引用。
		第12行，第27个字符：       内容【List<object>】  预定义类型“System.Object”未定义或导入
		第12行，第27个字符：       内容【List<object>】  未能在命名空间“System.Collections.Generic”中找到类型名“List<>”。此类型已转发到程序集“System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e”。请考虑添加对该程序集的引用。
		第12行，第32个字符：       内容【object】  预定义类型“System.Object”未定义或导入

---------------------------------------------------------------------------------------------

```
web工程直接是在源码的samples下创建的一个基于.net core2.2的 mvc工程，直接引用Natasha类库，动态编译的代码也很简单，只在生成的HomeController中随意增加了一段代码
```
       public IActionResult Index()
        {
            var code = @"
                var res_list = new List<object>();
                return res_list;
            ";

            FastMethodOperator.New.Using(new string[] { "System", "System.Linq", "System.Collections.Generic", " System.IO", "System.Threading.Tasks", "Newtonsoft.Json" })
                                .Param<object>("p")
                                .MethodBody(code)
                                .Return<object>()
                                .Complie<Func<object, object>>();

            Console.WriteLine("OK");

            return View();
        }
```
不知对于web工程是否还有特殊设置？

**Comment by NMSAzulX** [comment]
@wenjq0911 
你这个项目着急吗？  我看到源码中日志逻辑确实有错误，今晚准备修复，另外预定义类型“System.Object”未定义或导入这个问题，是roslyn的老问题了，我会尽快排查问题所在。

**Comment by wenjq0911** [comment]
> @wenjq0911
> 你这个项目着急吗？ 我看到源码中日志逻辑确实有错误，今晚准备修复，另外预定义类型“System.Object”未定义或导入这个问题，是roslyn的老问题了，我会尽快排查问题所在。

还在调研中，尚未实际使用

**Comment by NMSAzulX** [comment]
@wenjq0911 经排查，目前存在两个问题：

一、**打包方式**，Web项目的两种打包方式，目前来说独立打包可以解决引用上的: `Cannot find compilation library location for package 'Microsoft.AspNet.WebApi.Client' `问题。 

> 对此，我将持续关注官方动态，以便找到另一种打包的解决方案。

<br/>  

二、**致命问题**，mscorlib (即System.Private.CoreLib) 标准库打包但未引用。

>对此，3种解决方案：
>
   > 1、针对打包方式，提供一个独立打包的兼容API，以便Natasha可以指定文件夹进行引用加载。
>
   > 2、评估Natasha的引擎是否漏掉了某些环境配置(可能性不大)。
>
  >  3、临时解决方案：手动在web应用程序添加以下代码

```C#

var mscorlib = MetadataReference.CreateFromFile(typeof(object).GetTypeInfo().Assembly.Location);
 ScriptComplierEngine.References.Add(mscorlib);

```  

<br/>  

**建议**：

兄台，我建议您先采用临时解决方案，如果只是mscorlib的问题，我将对此提供一个Web环境的兼容API。  
如果在此过程中我找到了更好的解决方案，将通知你。  
如果解决方案还需要很久，而且在您开发过程中出现了其他问题，我将结合你的实际情况与我的测试结果做出一个可用的临时方案。

今晚有个更新是，DLL与运行时脚本混合编译。  
Web环境的还需要再磨合一下。

**Comment by wenjq0911** [comment]
> @wenjq0911 经排查，目前存在两个问题：
> 
> 一、**打包方式**，Web项目的两种打包方式，目前来说独立打包可以解决引用上的: `Cannot find compilation library location for package 'Microsoft.AspNet.WebApi.Client' `问题。
> 
> > 对此，我将持续关注官方动态，以便找到另一种打包的解决方案。
> 
> 
> 二、**致命问题**，mscorlib (即System.Private.CoreLib) 标准库打包但未引用。
> 
> > 对此，3种解决方案：
> > 1、针对打包方式，提供一个独立打包的兼容API，以便Natasha可以指定文件夹进行引用加载。
> > 2、评估Natasha的引擎是否漏掉了某些环境配置(可能性不大)。
> > 3、临时解决方案：手动在web应用程序添加以下代码
> 
> ```cs
> var mscorlib = MetadataReference.CreateFromFile(typeof(object).GetTypeInfo().Assembly.Location);
>  ScriptComplierEngine.References.Add(mscorlib);
> ```
> 
> 
> **建议**：
> 
> 兄台，我建议您先采用临时解决方案，如果只是mscorlib的问题，我将对此提供一个Web环境的兼容API。
> 如果在此过程中我找到了更好的解决方案，将通知你。
> 如果解决方案还需要很久，而且在您开发过程中出现了其他问题，我将结合你的实际情况与我的测试结果做出一个可用的临时方案。
> 
> 今晚有个更新是，DLL与运行时脚本混合编译。
> Web环境的还需要再磨合一下。

临时方案不可直接添加，昨日测试时候在创建CSharpCompilation对象时候添加了如下代码
```
.AddReferences(MetadataReference.CreateFromFile(typeof(object).GetTypeInfo().Assembly.Location))
```
发现添加后，发布打包后正常，但是vs调试运行后会报以下错误
```
第9行，第46个字符：       内容【Object】  类型“Object”同时存在于“System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e”和“System.Runtime, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a”中
```
临时方案也会出现此错误，目前采用预处理指令在非debug编译模式下添加代码处理，发布时候采用release编译
```
#if !DEBUG
                ScriptComplierEngine.References.Add(MetadataReference.CreateFromFile(typeof(object).GetTypeInfo().Assembly.Location));
#endif
```

**Comment by NMSAzulX** [comment]
@wenjq0911   
一个新的解决方案：`<MvcRazorExcludeRefAssembliesFromPublish>false</MvcRazorExcludeRefAssembliesFromPublish>`  发布方式可以选择依赖框架的方式，上面的标签要添加到web的项目文件中， 这个会在发布时自动生成refs子文件夹，Natasha中的组件会默认读取并引用，我在环境上测了一下，可以。

**Comment by NMSAzulX** [comment]
按错了。

**Comment by NMSAzulX** [comment]
临时方案会导致这个问题，因为调试环境的引用是全的，发布环境的引用不够全。

**Comment by WeihanLi** [comment]
能否默认加载常用类型的Assembly(比如 `typeof(object).Assembly`)，其他不常用的类库比如用户自己引用的第三方类库，提供一个方法让用户手动加载

**Comment by NMSAzulX** [comment]
@WeihanLi 
常用的Assembly,   目前已经是加载的。
另外手动方式已实现，v1.2.1.0版本，IComplier方法中添加了LoadFile，以便于添加第三方DLL。 
```C#  
 OopComplier oop = new OopComplier();
 oop.LoadFile(@"D:\Project\IlTest\ClassLibrary1\bin\Debug\netstandard2.0\ClassLibrary1.dll");
 Type type = oop.GetClassType(text);
```

**Comment by NMSAzulX** [comment]
@wenjq0911 若没有问题，今晚下班前将关闭这个issue.
